notifications:
  email: false

sudo: true

branches:
  only:
  - master

compiler:
  - gcc
os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: deb http://www.emdebian.org/debian/ squeeze main
    update: true
    packages:
    - g++-7

install:
  - if [ $CXX == g++ ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then CXX=g++-7; fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get install binutils-mips-linux-gnu --allow-unauthenticated
    fi

before_script:
  - git clone https://github.com/mipt-ilab/mipt-mips
  - mkdir sim && cd sim
  - cmake $TRAVIS_BUILD_DIR/simulator -DCMAKE_BUILD_TYPE=Debug && make
  - cd ..

script:
  - make all
  - ./.run-tests.sh

