notifications:
  email: false

language: cpp
dist: xenial

branches:
  only:
  - master

compiler:
  - clang
os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: deb http://www.emdebian.org/debian/ squeeze main
    update: true
    packages:
    - libboost-dev
    - libstdc++-7-dev
    - ninja-build

install:
  - pip install --user future
  - sudo apt-get install binutils-mips-linux-gnu --allow-unauthenticated

before_script:
  - git clone https://github.com/mipt-ilab/mipt-mips --depth=1
  - mkdir sim && cd sim
  - cmake $TRAVIS_BUILD_DIR/mipt-mips/simulator -DCMAKE_BUILD_TYPE=Debug -G Ninja && ninja
  - cd ..

script:
  - make
  - ./.run-tests.sh $TRAVIS_BUILD_DIR/sim/mipt-mips

