notifications:
  email: false

sudo: true

branches:
  only:
  - master

compiler:
  - gcc
os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: deb http://www.emdebian.org/debian/ squeeze main
    update: true
    packages:
    - g++-7
    - libboost-dev

install:
  - sudo apt-get install binutils-mips-linux-gnu --allow-unauthenticated

before_script:
  - git clone https://github.com/mipt-ilab/mipt-mips
  - mkdir sim && cd sim
  - CXX=g++-7 cmake $TRAVIS_BUILD_DIR/mipt-mips/simulator -DCMAKE_BUILD_TYPE=Debug && make
  - cd ..

script:
  - make all
  - ./.run-tests.sh $TRAVIS_BUILD_DIR/sim/mipt-mips

