notifications:
  email: false

language: cpp
dist: bionic

branches:
  only:
  - master

os: linux

addons:
  apt:
    sources:
    - sourceline: deb http://www.emdebian.org/debian/ squeeze main
    update: true
    packages:
    - libboost-dev
    - ninja-build
    - python3

install:
  - sudo apt-get install binutils-mips-linux-gnu --allow-unauthenticated

before_script:
  - git clone https://github.com/mipt-ilab/mipt-mips --depth=1 --recursive
  - mkdir sim && cd sim
  - cmake $TRAVIS_BUILD_DIR/mipt-mips/simulator -DCMAKE_BUILD_TYPE=Debug -G Ninja && ninja
  - cd ..

script:
  - make
  - ./.run-tests.sh $TRAVIS_BUILD_DIR/sim/mipt-mips
